### ISSUE TITLE
Concentrar leitura de configurações no settings.py

### ISSUE THREAD

**Issue by cuducos** [vmesel/PyJobs#106]
Reparo que em diversos arquivos temos a leitura de configurações: `settings.py`, `utils.py`, `newsletter.py` e `views.py`. Proponho fazer toda a leitura dessas configurações e nos demais lugares ler as configurações de `django.conf.settings`. Ou seja:

1. Concentrar todas ocorrências do `decouple.config` no `settings.py` (removendo essas ocorrências de `settings.py`, `utils.py`, `newsletter.py` e `views.py`)
2. Alterar esses 4 arquivos utilizando a estrutura como a do exemplo a seguir:

```python
# utils.py
from django.conf import settings
from telegram import Bot, TelegramError


def post_telegram_channel(message):
    if not settings.TELEGRAM_TOKEN and not settings.TELEGRAM_CHATID:
        return False,  'missing_auth_keys'

    bot = Bot(settings.TELEGRAM_TOKEN)
    try:
        bot.send_message(chat_id=settings.TELEGRAM_CHATID, text=message)
    except TelegramError:
        return False, 'wrong_auth_keys'

    return True, 'success'
```

Isso é importante pois caso haja alguma falha na leitura ou configuração das variáveis isso já é detectado na hora da inicialização do Django, e não no meio da UX.

**Comment by vmesel** [comment]
@cuducos faz super sentido! Quer tocar isso?

**Comment by cuducos** [comment]
> @cuducos faz super sentido! Quer tocar isso?

Mandei uma proposta no #109 ; )

**Comment by vmesel** [comment]
Resolvido!
