### ISSUE TITLE
Área do Pythonista - Adicionar Visualizar minhas cadidaturas

### ISSUE THREAD

**Issue by fcschmidt** [vmesel/PyJobs#127]
Área do Pythonista temos:
- **Atualizar seu Perfil**
- **Atualizar sua senha**
- **Visualizar Vagas**

Uma feature adicional:
- **Visualizar minhas candidaturas**
Nela o pythonista poderia visualizar todas as sua candidaturas.

**Comment by vmesel** [comment]
@fcschmidt show! Curti a idéia! Está afim de implementar? Quero ver como fazer isso do lado da empresa também!

**Comment by fcschmidt** [comment]
@vmesel Vou começar a implementar. Inclusive para área da empresa, disponibilizar uma função que permite a empresa encerrar a vaga. Assim apareceria um badge na vaga dizendo que foi fechada ou encerrada.

**Comment by vmesel** [comment]
Pode abrir um outro issue com isso? Acho que é bem válido!

**Comment by vmesel** [comment]
Na nova branch `fix/pip-file` e no ar já está a versão preliminar desta ferramenta! Portanto o problema está resolvido! Fechando issue!
