### ISSUE TITLE
[Área da empresa] - Adicionar uma nova funcionalidade para empresa encerrar a vaga

### ISSUE THREAD

**Issue by fcschmidt** [vmesel/PyJobs#128]
**Área da empresa:** 
- Criar uma funcionalidade que permita a empresa encerrar uma vaga em aberto.
- Na página da vaga:
   - Adicionar um badge/Botão, no lugar do botão **Aplicar para esta vaga pelo Pyjobs**  dizendo que a mesma foi fechada/encerrada, processo seletivo encerrado.

**Comment by vmesel** [comment]
@fcschmidt cara, obrigado pela paciência.

Curto a ideia, mas a questão é como deixamos esse processo de cadastro de vaga sem fricção para podermos não fazer a empresa sair do site?

Terminamos o cadastro dela via e-mail?

**Comment by vmesel** [comment]
Feita pelo @cuducos! Valeu queridão!
