### ISSUE TITLE
Melhorar exibição, das informações da vaga, na hora de compartilhar

### ISSUE THREAD

**Issue by diegosorrilha** [vmesel/PyJobs#154]
A ideia é utilizar as meta tags `og` para melhorar a experiência de compartilhamento das vagas.

A sugestão é:
```
<meta property="og:title" content="Título da vaga">
<meta property="og:description" content="Conteúdo principal da vaga">
```

**Comment by vmesel** [comment]
@diegosorrilha quer tocar isso? Estou enrolado com outros aspectos do site e preciso focar neles. Se precisar de ajuda para localizar o template ou as informações, fique a vontade para me chamar no telegram!

**Comment by diegosorrilha** [comment]
@vmesel Beleza! Vou tocar então. 

Essa semana estou um pouco enrolado também. Mas assim que der eu pego para mexer nisso e qualquer coisa te chamo no telegram. ;)
