### ISSUE TITLE
Criar novo handler de login

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#158]
Hoje em dia, permitimos apenas login via usuário e não via e-mail, precisamos permitir isto!

**Comment by isouzasoares** [comment]
@vmesel alguém começou a tocar isso? Posso fazer no decorrer da semana?

**Comment by vmesel** [comment]
@isouzasoares manda bala!

**Comment by walison17** [comment]
> Hoje em dia, permitimos apenas login via usuário e não via e-mail, precisamos permitir isto!

percebi que vc ta usando o user model padrão do django e não ta fazendo nenhuma validação de email único no form de registro, trocar o user model com o projeto em andamento é bem complicado ..

**Comment by vmesel** [comment]
Sim @walison17, vou deixar sem isto por enquanto! Many tks

**Comment by isouzasoares** [comment]
Concordo com @walison17. Talvez mais a frente poderiamos validar de colocar django-allauth com auth social.
