### ISSUE TITLE
Filtro de trabalho remoto

### ISSUE THREAD

**Issue by rafinharamos** [vmesel/PyJobs#164]
Fazer filtro para facilitar quem só procura trabalho remoto

**Comment by cptx032** [comment]
Eu acho que na página principal esse filtro já existe:

![image](https://user-images.githubusercontent.com/12432805/66592703-f8d13900-eb6b-11e9-9ee7-9720122d12a6.png)

seria esse?

Ele só não filtra as vagas em destaque

**Comment by vmesel** [comment]
Feito!
