### ISSUE TITLE
Adicionar campos para faixa salarial

### ISSUE THREAD

**Issue by Carioca** [vmesel/PyJobs#17]
- Campos mínimo/máximo nos modelos
- Campos mínimo/máximo na criação de um Job
- Interface de busca
  - Pode ser campos num primeiro momento
  - Considerar um double slider depois (por exemplo: https://api.jquerymobile.com/rangeslider/ )

**Comment by hebertjulio** [comment]
Esses campos teriam que ser opcionais, certo!?

**Comment by vmesel** [comment]
@Carioca bem interessante, @hebertjulio consegue tocar isso?

**Comment by hebertjulio** [comment]
@vmesel posso fazer sim. :)

E esses campos serão obrigatórios?

**Comment by vmesel** [comment]
Não! Pode fazer como se eles fossem campos adicionais @hebertjulio !
