### ISSUE TITLE
Testar no Django 2.2

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#186]
Criar um virtualenv instalando Django<2.3 e rodar os testes.

Reportar aqui o resultado dos testes.

**Comment by vmesel** [comment]
Devemos testar toda a aplicação para que possamos passar de versão do Django para as mais recentes. Estamos com uma LTS estável, porém o período de fim de suporte se aproximará em breve e precisamos estar mais livres de bugs o possível.

**Comment by novais03** [comment]
eu quero pega-lá

**Comment by vmesel** [comment]
@novais03 valeu pela iniciativa! Se precisar de ajuda, fala comigo! 

Estou fazendo também para aprender, mas não commitarei nada sem falar contigo!

**Comment by gprotasio** [comment]
Acho que esse issue pode ser fechado, o que vocês acham? @viniciusban @vmesel @novais03

**Comment by vmesel** [comment]
Fechado pela PR #206
