### ISSUE TITLE
Adicionar campo de tipo de contratação (CLT, PJ, Freela, CLT ou PJ, A discutir)

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#189]
@vmesel detalha aí

**Comment by vmesel** [comment]
Precisamos permitir com que empresas possam inserir vagas com diferentes modos de contratação, assim poderemos também ter freelas e outras modalidades de contratação diferenciadas.

**Comment by gprotasio** [comment]
Pode designar esse tópico para mim. @vmesel @viniciusban

**Comment by vmesel** [comment]
Resolvido no PR #221
