### ISSUE TITLE
Form de criação de vaga

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#194]
@vmesel detalha aí

**Comment by vmesel** [comment]
Para podermos melhorar o form, precisamos realizar algumas atividades:

- Tirar a lógica do recaptcha da view (pensamento de slim views, fat models and others)
- Arrumar o layout do form de criação para ser responsível no mobile de uma forma legível.

**Comment by pepcmarques** [comment]
posso tentar este... manda pra mim

**Comment by pepcmarques** [comment]
Dúvida sobre "Tirar a lógica do recaptcha da view"
Este "view" refere-se ao padrão MVC e não ao padrão Django MVT, certo?
A ideia aqui é retirar o re-captcha do template?

**Comment by vmesel** [comment]
A idéia aqui é tirar a lógica da requisição válida de dentro da view.py.

Você pode fazer isso sobreescrevendo o método save do formulário e adicionando a lógica do request ou a do is_valid.

**Comment by vmesel** [comment]
@pepcmarques acabei confundindo qual tu ia pegar e resolvi esse aqui nesta branch: #199 

Faz um code review para tu ver se faz sentido essa solução para nós!
Acho que seria interessante tu pegar o do form de contatos #190 para fazer o mesmo processo.

Que tal?

**Comment by pepcmarques** [comment]
@vmesel, desculpe a demora na resposta deste.

Pode deixar. Vou só esperar o @viniciusban e vc fazerem o review e o merge. Daí eu ataco o [#190](https://github.com/vmesel/PyJobs/issues/190).
