### ISSUE TITLE
Melhorar responsividade do portal para podermos permitir aos usuários melhor atualização de formulários

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#195]
@vmesel detalha aí.

**Comment by vmesel** [comment]
Os forms de atualização de vagas devem ser quebrados para ter uma visualização melhor.

Atualmente, cada linha tem o nome do campo e o campo em si envolto de uma tag div de classe `form-group`, mas a visualização melhor seria o nome do campo acima e o campo embaixo.
