### ISSUE TITLE
Descobrir como deixar designar uma issue a uma pessoa

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#197]
@vmesel please, pra evitar que duas pessoas peguem a mesma issue.

**Comment by vmesel** [comment]
@viniciusban eu não encontrei nada nas confs do projeto. Como eu deveria procurar isso? Até onde eu sei, a pessoa pode se auto associar àquela issue. Correto?

**Comment by gprotasio** [comment]
O responsável que receberá a atribuição do Issue, tem que ser participante do projeto.

https://help.github.com/pt/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users

**Comment by gprotasio** [comment]
@viniciusban @vmese 
![Screen Shot 2019-11-19 at 16 20 27](https://user-images.githubusercontent.com/54383772/69178549-9d8a5300-0ae8-11ea-889a-bf9d603a14ab.png)

**Comment by novais03** [comment]
Estou a disposição de vocês.

**Comment by meselfiap** [comment]
Teste!

**Comment by gprotasio** [comment]
Acho que esse issue pode ser fechado, o que vocês acham? @viniciusban @vmesel @novais03

**Comment by vmesel** [comment]
Por enquanto, vamos deixar do jeito que está no GitHub... Em breve, podemos migrar para outro issue tracker!
