### ISSUE TITLE
Adicionar favicon

### ISSUE THREAD

**Issue by ffreitasalves** [vmesel/PyJobs#20]
Poderia ter o próprio favicon do python.org que está no github deles

https://github.com/python/pythondotorg/blob/master/static/favicon.ico

**Comment by vmesel** [comment]
Então usar o do Python pode ter alguns problemas de legalidade... Precisamos bolar um logo e um favicon para fazer isso.

**Comment by vmesel** [comment]
Caso necessário, irei reabrir este issue!
