### ISSUE TITLE
Melhorar o sistema de busca

### ISSUE THREAD

**Issue by novais03** [vmesel/PyJobs#202]
Procurei vagas por salário:

Exemplo:  acima de 21.000,00 e e a pesquisa não retornou a busca corretamente.

**Comment by novais03** [comment]
As opções são retornadas abaixo da opção de busca, mas como tem vagas aleatórias acima, causa confusão.

**Comment by vmesel** [comment]
Olá @novais03!

Você poderia utilizar o seguinte template desta issue para podermos entender qual o problema?

```
**Descreva o bug**
Uma descrição clara e concisa do bug.

**Passo a passo para reproduzir**
1. Vá para '...'
2. Clique em '....'
3. Desça a página até  '....'
4. Veja o erro

**Resultado esperado**
Descrição clara e simples sobre sua expectativa do que aconteceria.

**Screenshots**
Se aplicáveis, coloque alguns screenshots para permitir a melhor visualização
```

**Comment by vmesel** [comment]
Fechando a issue para podermos discutir e estruturar melhor isso.
