### ISSUE TITLE
Melhorias nos cards de anúncio de vagas

### ISSUE THREAD

**Issue by rennerocha** [vmesel/PyJobs#217]
Os cards com a descrição da vaga é um mapeamento um-para-um dos campos do banco de dados. Não é visualmente tão agradável na minha opinião.

Seguindo a sugestão desse [tweet](https://twitter.com/addyosmani/status/1229329639056846851), reorganizar as informações retirando elementos que não tem necessidade (por exemplo não é necessário falar `Localidade: Nome da Cidade`, só de colocar NomeDaCidade-SP diminui a poluição visual). Acho que isso pode ser trabalhado nos outros campos também.

**Comment by vmesel** [comment]
Poluição visual diminuída no #221
