### ISSUE TITLE
Padronização de filtros nas telas de buscas de vagas

### ISSUE THREAD

**Issue by jhonatanlteodoro** [vmesel/PyJobs#218]
## Problema
Atualmente na tela inicial de busca temos algumas opções de filtros para as vagas como, nível, localidade e etc... Contudo, na tela seguinte temos apenas nível e titulo da vaga.
Veja as imagens abaixo

**Primeira tela**
![image](https://user-images.githubusercontent.com/32911546/75875565-b6e2b100-5df2-11ea-9652-6a8344317958.png)

**Segunda Tela**
![image](https://user-images.githubusercontent.com/32911546/75875634-d37ee900-5df2-11ea-900d-2d3887c7b9ef.png)

## Sugestão
Talvez fosse interessante manter todos os filtros em ambas as telas, para quem está pesquisando.
Por exemplo, no meu caso eu frequentemente uso o pyjobs para avaliar as buscas do mercado, níveis de exigências, empresas que estão contratando, faixa salarial, onde essa galera está e entre outras coisas. Naturalmente, durante as buscas eu preciso voltar para tela anterior quando quero um filtro de outra cidade por exemplo ou faixa salarial e isso é um pouco incômodo.

**Comment by diegosorrilha** [comment]
Seria uma boa mesmo!

**Comment by vmesel** [comment]
Resolvido no PR #220
