### ISSUE TITLE
Incorporar descrição e formulário de job em um site

### ISSUE THREAD

**Issue by mayckxavier** [vmesel/PyJobs#219]
## Cenário pensado inicialmente
1. Usuário cadastra vaga no PyJobs;
2. PyJobs fornece código HTML do formulário (ou outro modo) para incorporação num website;
3. Usuário formata css como quiser e adapta à identidade visual dele;

**Comment by vmesel** [comment]
@mayckxavier como podemos implementar isso? Tem alguma dica?

Um botão estilizado com o href para o site serviria?
