### ISSUE TITLE
Adicionar PEP8

### ISSUE THREAD

**Issue by hudsonbrendon** [vmesel/PyJobs#23]
Adicionar PEP8 enquanto o projeto é 'pequeno' e de fácil manutenção.

**Comment by vmesel** [comment]
Muito boa a ideia e acho que devemos seguir a PEP8, talvez o flake8 com algumas exceções!

**Comment by hudsonbrendon** [comment]
Eu sou super a favor do flake8,  com a excessão do número máximo de caracteres, costumo adotar os 120.

**Comment by cuducos** [comment]
Que tal adicionar um CI de qualidade de código como o Landscape.io ou o Code Climate?

**Comment by vmesel** [comment]
@cuducos podemos trabalhar nisso! Quais seriam os próximos passos para poder colocar isso no projeto?

**Comment by cuducos** [comment]
Eu realmente acho os reports do Landscape melhor, mas eles estão sobrecarregados e [não sei se tá rolando check automático em repositórios free](https://hugs.landscape.io). De qualquer forma o processo é o mesmo para as duas pataformas:

1. Registrar o repositório no site deles
2. Adicionar as configurações no repositório (`.codeclimate.yml` ou `.landscape.yml`) com as opções desejadas
3. Se quiser, adicionar o badge no `README.md`

**Comment by vmesel** [comment]
#41 adiciona o CodeClimate

**Comment by Mdslino** [comment]
#17

**Comment by vmesel** [comment]
Fechando issue já que o Django não respeita a PEP 8, porém tem seu próprio styleguide!
