### ISSUE TITLE
Paginação não indica em que página você está

### ISSUE THREAD

**Issue by Mdslino** [vmesel/PyJobs#267]
Quando acessamos a listagem de vagas não é possível saber em qual página estamos pelo navegador de paginação.

Como é possível ver na URL estamos na página 2
![url](https://user-images.githubusercontent.com/8658544/113508112-89e85c80-9524-11eb-95d9-fa47f395b781.PNG)

Porém isso não é indicado de forma clara no site
![paginação](https://user-images.githubusercontent.com/8658544/113508116-8e147a00-9524-11eb-8f83-91b376f42d34.PNG)

Sugestão. Mudar a cor da página atual no seletor de página, assim destacando a página atual.

**Comment by vmesel** [comment]
@Mdslino tks pelo report! vou arrumar isso!

**Comment by vmesel** [comment]
![image](https://user-images.githubusercontent.com/4984147/118032024-92129380-b33d-11eb-961f-6c2a7fe77fd2.png)
Resolvido
