### ISSUE TITLE
Criar página de Pricing e de Entre em contato

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#31]
Criar página que permita a empresa ver os pricings e entender as facilidades que são propostas pelo projeto do PyJobs.

**Comment by Mdslino** [comment]
Quais iram ser os preços, modelo de monetização e formas de pagamento?

**Comment by vmesel** [comment]
@Mdslino estou desenvolvendo isso ainda! Não quero que seja algo agressivo no momento!
