### ISSUE TITLE
Organizar requirements.txt

### ISSUE THREAD

**Issue by GuilhermeVBeira** [vmesel/PyJobs#35]
separarar em dois arquivos libs de desenvolvimento e libs de produção

**Comment by vmesel** [comment]
@GuilhermeVBeira qual seria a real necessidade disso? Você vê alguma biblioteca que deva ser somente nos requirements.txt desenvolvedores

**Comment by GuilhermeVBeira** [comment]
Então @vmesel , tem algumas libs por exemplo ipython, jedi, psycopg2 que podem ser removidas pois não são utilizadas no desenvolvimento. Hoje a noite vou dar uma separada.
