### ISSUE TITLE
Adicionar filtro de vagas

### ISSUE THREAD

**Issue by hudsonbrendon** [vmesel/PyJobs#37]
- [ ] Campo para pesquisa de vagas
- [ ] Filtragem por home office
- [ ] Filtragem por tipo do job

OBS: Na filtragem do campo de pesquisa, recomendo utilizar o https://github.com/etianen/django-watson para auxiliar em buscas avançadas.

**Comment by vmesel** [comment]
@hudsonbrendon tu já tem experiência nisso? Tais afim de tocar?

**Comment by hudsonbrendon** [comment]
@vmsel tenho sim, posso ficar responsável por essa task

**Comment by vmesel** [comment]
#45 PR fecha este issue!
