### ISSUE TITLE
Criar APIs para cadastro de jobs

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#42]
Criar uma API Restful no formato JSON que permita a um usuário com login já cadastrado na plataforma, cadastrar uma vaga para a empresa. Para esta mesma vaga, ter um endpoint com autenticação que retorna os profissionais relacionados a ela.

**Comment by Mdslino** [comment]
Como anda essa parte? Posso ajudar nesse quesito.

**Comment by vmesel** [comment]
@Mdslino está parada! Pode tocar!
