### ISSUE TITLE
Escrever guidelines de contribuição para o projeto

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#46]
O arquivo de contributions tem muita importância para o projeto se manter organizado. Preciso sentar a bunda na cadeira e escrever com muito carinho e amor o arquivo de contributions para podermos elevar o nível de qualidade deste código!

**Comment by hudsonbrendon** [comment]
Uma sugestão que eu tenho é a de passar todo o código do projeto para inglês, em alguns lugares está misturado inglês e português (variáveis, funções, classes, etc).

**Comment by giovanisleite** [comment]
Pode criar uma nova issue, @hudsonbrendon?

**Comment by vmesel** [comment]
@giovanisleite @hudsonbrendon como dito no outro issue que não foi referenciado aqui (#47), precisamos primeiro testar, depois disto feito, conseguimos traduzir o projeto e constatar possíveis problemas!
