### ISSUE TITLE
Migrar o código em português para inglês

### ISSUE THREAD

**Issue by hudsonbrendon** [vmesel/PyJobs#47]
Atualmente várias partes do projeto encontra-se com código em português, seria interessante que para termos um código mais conciso e de fácil manutenção, utilizar-mos apenas o inglês em nomes de variáveis, funções, classes, etc.

**Comment by vmesel** [comment]
Será que não seria melhor fazer o inverso? Para migrarmos isso, acredito que seja melhor fazer a cobertura de testes crescer antes, para depois podermos dar suporte a versão com novas variáveis!
Como o foco do PyJobs é Brasil por enquanto, acredito que devamos prestar um serviço maior ao português!

**Comment by hudsonbrendon** [comment]
Eu voto no inglês, qualquer desenvolvedor que se prese sabe o básico de inglês, pelo menos pra programar oque é uma realidade na grande maioria que colabora no Github. Sou a favor da cobertura de testes antes de fazermos isso, mas acredito que teria que ser algo pra agora, esperar o projeto crescer mais acabaria complicando ainda mais as coisas, de qualquer forma sobre o inglês x português, da uma olhada nesse vídeo quem sabe te convensa :) 

https://www.youtube.com/watch?v=xWbuHZcS8gA

**Comment by vmesel** [comment]
Cara, resposta simples e rápida! Testes primeiro, depois a gente remonta tudo em um padrão só! Não considero um problema isto no momento, a minha maior preocupação é resolver a dor das empresas!

**Comment by vmesel** [comment]
Será fechado para abertura quando tivermos no sprint para resolver este problema!
