### ISSUE TITLE
Organizar estrutura do projeto

### ISSUE THREAD

**Issue by hebertjulio** [vmesel/PyJobs#52]
Durante a implementação dos campos para faixa salarial percebi que o projeto não está muito bem estruturado. Por exemplo, temos uma view no aplicativo chamado "core" que cadastra nova vaga e ao mesmo tempo cadastra empresa, e outra view que edita a vaga em um aplicativo chamado "jobs". Neste caso, como sugestão poderíamos ter uma aplicação empresas com views para gerenciamento de empresas e no aplicativo "jobs" ter em uma view apenas o cadastro e edição de vagas.

**Comment by vmesel** [comment]
Concordo, precisamos re-implementar os pontos que você disse!

**Comment by vmesel** [comment]
Irei reabrir este Issue com um roadmap para a versão do Django 2.0!
