### ISSUE TITLE
Adicionar docker como ambiente de desenvolvimento

### ISSUE THREAD

**Issue by hudsonbrendon** [vmesel/PyJobs#58]
Creio que seria interessante adicionar o docker como opção pra quem quer contribuir com o projeto assim como é feito no speakerfight por exemplo: https://github.com/luanfonceca/speakerfight

Posso ficar a frente disso ...

**Comment by vmesel** [comment]
@hudsonbrendon mete ficha! Só preciso depois que tu ajude a manter o suporte!

**Comment by hudsonbrendon** [comment]
Claro man, qualquer coisa é só falar!
