### ISSUE TITLE
Não consigo resetar a senha !

### ISSUE THREAD

**Issue by MrLucasCardoso** [vmesel/PyJobs#66]

**Comment by GuilhermeVBeira** [comment]
Em qual parte parou de funcionar?

**Comment by MrLucasCardoso** [comment]
O email não ta chegando. assim que desse eu iria olhar e ver se não era no código, pra mandar um PR.

**Comment by vmesel** [comment]
Acredito que está funcionando sim! @MrLucasCardoso já resolveu?

**Comment by MrLucasCardoso** [comment]
Testei aqui novamente e o email não chegou
