### ISSUE TITLE
Pesquisa de vagas

### ISSUE THREAD

**Issue by rdenadai** [vmesel/PyJobs#67]
Não sei se é válido, mas talvez seja interessante ter uma pesquisa de vagas no site.

Talvez pesquisar por:
 - Palavra chave
 - Cidade / Estado / Remoto

**Comment by vmesel** [comment]
Importante! Vamos trabalhar nisto!

**Comment by rdenadai** [comment]
Posso contribuir nessa implementação @vmesel

**Comment by vmesel** [comment]
@rdenadai feel free to help! Hehehe toda ajuda é bem vinda!

**Comment by rdenadai** [comment]
Fechado @vmesel, fork realizado, e já criei uma branch para trabalhar:

https://github.com/rdenadai/PyJobs/tree/wip_issue_%2367

Em breve faço um PR para sua análise!

**Comment by rdenadai** [comment]
@vmesel implementada uma pesquisa simples de vagas, e gerado o PR #70

**Comment by vmesel** [comment]
Fechado com o PR do @rdenadai! Excelente código!
