### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by GuilhermeVBeira** [vmesel/PyJobs#69]
Forçar o uso do https no site todo

**Comment by vmesel** [comment]
Preciso analisar como fazer isto @GuilhermeVBeira !

**Comment by vmesel** [comment]
@rdenadai tenho que dar uma olhada nisso... não sei o quanto fácil é implementar isto no heroku, vou pesquisar enquanto isto! Fechando a Issue, pois não vou consertar agora...

**Comment by rdenadai** [comment]
@vmesel tenho conta no heroku também, posso ajudar nessa questão... 

https://devcenter.heroku.com/articles/ssl-endpoint
https://devcenter.heroku.com/articles/ssl

**Comment by GuilhermeVBeira** [comment]
Porque fechar a issue? já foi solucionada? Não acho uma boa pratica fechar sem solucionar, até porque ela provavelmente seja reaberta em seguida.

Sobre a solução caso o @rdenadai queira, posso enviar hoje a noite.

**Comment by rdenadai** [comment]
@GuilhermeVBeira acho que o @vmesel aprecia toda a ajuda possível... tem como testar a questão do https no heroku como ele mencionou?

Acho que não conseguirei testar isso hoje... talvez durante a semana possa contribuir.
