### ISSUE TITLE
URGENTE: Atualizar o Django

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#71]
Devemos atualizar o django para o django 2.0 para podermos ter suporte no Python 3.7

**Comment by rdenadai** [comment]
@vmesel em alguns testes que fiz, consegui atualizar para Python 3.7 com o Django 2.0.8 sem problemas... para a latest houve maior quebra de compatibilidade então talvez tenha mais problemas nisso.

**Comment by rdenadai** [comment]
@vmesel testes iniciais com essa branch mostraram o que disse no meu comment acima...

https://github.com/rdenadai/PyJobs/tree/wip_issue_%2371

**Comment by HigorMonteiro** [comment]
@vmesel  como anda a atualização do pyjobs para o django 2.0, vi que nosso amigo @rdenadai já esse trabalho inclusive  parabéns pelo trabalho, com essa atualização pensei em algumas melhorias como o uso do [Pipenv](https://pipenv.readthedocs.io/en/latest/) para melhorar a questão das dependências e também o uso das [CBVs](https://docs.djangoproject.com/en/2.1/topics/class-based-views/).

**Comment by rdenadai** [comment]
@HigorMonteiro já temos versões mais novas do django... a qual ainda não testei... mas com certeza vai ter uma quebras devido a compatibilidade de algumas funcionalidades do django em sua versão mais recente.

Assim que tiver um tempinho extra (devido ao mestrado tou atolado por enquanto de coisa para fazer), vou ver se consigo ajudar o @vmesel na empreitada para migrar para versões mais acima... provavelmente farei isso na branch que citei assim...

Não vejo problema em adicionar melhorias como o Pipenv... mas não sei se as Class Base Views, não darão um retrabalho ainda maior... mas seria talvez mais simples para adicionar testes dessa maneira.

Até

**Comment by vmesel** [comment]
Pessoal, estou enrolado com o trabalho e as provas da faculdade nos últimos tempos. Posso ajudar a vocês fazerem as contribuições do Hacktoberfest!

Criei um grupo do telegram: https://t.me/joinchat/Cc8X5A-re7F8F4AIP0lSeg

**Comment by vmesel** [comment]
Pessoal, devemos atualizar o Django urgente! Surgiu um patch para algumas vulnerabilidades do 1.11 e creio que devamos fazê-lo para atendermos a todos com a devida segurança.

**Comment by vmesel** [comment]
Após ler um pouco, descobri que ainda existem versões da 1.11.X suportadas, instalei a 1.11.15 e ela corrige a vulnerabilidade de segurança do sistema! Mas mesmo assim precisamos mudar de Django 1.X para 2.X

**Comment by rdenadai** [comment]
@vmesel suave cara, acho que a migração para a lastest da versão 1 do django já ajuda momentaneamente.

Assim que possível vou voltar a minha branch de teste da migração do django e ajudá-lo na migração... mas como mencionei acima, no meu primeiro comentário nesta issue, provável que daria para migrar para a 2.0.8 sem problemas.

**Comment by vmesel** [comment]
@rdenadai @HigorMonteiro por enquanto a versão 1.11.15 está sendo de bom grado e acabei de olhar no site do Django, a 1.11 é um LTS, então teremos mais 2 anos para atualizar o Django (obviamente que eu não espero fazer neste tempo, gostaria de tocar nisto em dezembro). [Django Versions and it's support](https://www.djangoproject.com/download/)

**Comment by vmesel** [comment]
Irei fechar este Issue por enquanto em detrimento de testes no momento, acredito que devamos fazê-los antes de migrarmos de versão de Django.
