### ISSUE TITLE
Adicionar codecov

### ISSUE THREAD

**Issue by ikaromn** [vmesel/PyJobs#74]
Seria uma boa adicionar o codecov para manter uma boa cobertura dos testes.

**Comment by vmesel** [comment]
@ikaromn qual a sua sugestão de uso para o Code Cov? Hoje em dia eu sei que o site tem uma cobertura pequena de testes, mas o quão importante é o número de testes?

Uma palestra do Eduardo Mendes (se eu não me engano) mostrou que você pode ter uma cobertura de testes em seu código de 100% mas não estar realmente testando algo. Não sei se isto seria uma métrica boa para a gente utilizar.

PS: Aceito sugestões
