### ISSUE TITLE
Trocar engine do TastyPie para Django Rest Framework

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#81]
O tastypie serviu o propósito dele muito bem, mas como queremos avançar com o projeto, devemos incluir o Django Rest Framework como repositório padrão para as nossas APIs. Além de ser um projeto bem mais sólido que o TastyPie, ele conta com as "views" de CRUD já feitas, o que torna o desenvolvimento uma mão na roda!

**Comment by leportella** [comment]
uma opção mais simples e menos verborrágica que o TastyPie é o restless (que é a evolução do TastyPie de acordo com o criador)

Tenho um post pra ajudar: http://leportella.com/english/2017/04/03/make-endpoints-using-restless.html

O projeto original é: https://github.com/toastdriven/restless

**Comment by vmesel** [comment]
@leportella obrigado pela sugestão! Vou dar uma olhada no seu blog post para avaliar essa decisão!

**Comment by viniciusemerald** [comment]
@cuducos feel free to use what you want! xD

Se tu falou, tá falado! Essa parte de frameworks de CRUD eu sou bem crú, eu gosto de fazer na munheca, mas por tempo ábil ficou difícil implementar aqui no PyJobs (custo(tempo) x benefício também não era tão alto)
