### ISSUE TITLE
Refatorar algumas lógicas do Model para Managers

### ISSUE THREAD

**Issue by Marlysson** [vmesel/PyJobs#90]
Estava dando uma olhada no código e vi que possui algumas queries com alguma lógica dentro dos models, o que acha de movê-los para algum manager e assim essa lógica ou query complexa ficar desacoplada?

Exemplo:

https://github.com/vmesel/PyJobs/blob/master/pyjobs/core/models.py#L61

**Comment by HigorMonteiro** [comment]
@Marlysson e uma ideia super valida, eu fiz uma pequena refatoração justamente nesse ponto que você comentou, tá no PR #91 acredito que com a mudança para as CBVs vamos limpar muita coisa no models, qualquer coisa entra no grupo no telegram que podemos discutir mais sobre essa refatoração :)

**Comment by HigorMonteiro** [comment]
@Marlysson https://t.me/joinchat/Cc8X5A-re7F8F4AIP0lSeg :)

**Comment by cuducos** [comment]
Acho que uma forma de começar seria automatizando a análise de cobertura dos testes. Assim vemos o que não está sendo coberto, e priorizamos o que é mais crucial…

Posso começar nessa issue com isso? Algum serviço de CI de preferência para isso?

**Comment by viniciusemerald** [comment]
@cuducos pode começar com isso! Many tks pelo help!

Pode começar na issue de testes #89

**Comment by vmesel** [comment]
@cuducos agora que a issue #96 já foi resolvida, bora meter a mão na massa? hehehe

**Comment by cuducos** [comment]
> @cuducos agora que a issue #96 já foi resolvida, bora meter a mão na massa? hehehe

Bom, primeiro eu precisava de um ambiente Docker mais confiável. Coisas que eu propûs no #93 se perderam e tentei reintroduzí-las no #98. Quando esse estiver funcionando, mando a contribuição de teste coverage ([dessa branch aqui](https://github.com/cuducos/PyJobs/tree/test-coverage)) e aí sim acho que temos um stack bom para pensar na #89 ; )

**Comment by cuducos** [comment]
Depois do 847594974014bb1b90e3082fa9038526b61da81e e, principalmente, do 6196ea30f3dc755b9398e635a70f42687932b649, acho que precisamos melhorar um pouco a descrição dessa _issue_ especificando o que pode ainda ser refatorado… ou é frescura minha?
